version: "2.1"

services:
  chrome:
    container_name: chrome
    image: selenium/node-chrome:4.0.0-beta-3-20210426 
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - START_XVFB=false
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    networks:
      net:

  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub:4.0.0-beta-3-20210426
    environment:
      - START_XVFB=false
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      net:

networks:
  net:
    external: true
    name: projects_net